-- PCA Documents table
-- Stores the Planificación Curricular Anual documents generated by AI.
-- The docente fills the form, AI generates content, payment unlocks it.

CREATE TABLE `pca_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sessionId` varchar(320) NOT NULL COMMENT 'email del docente o deviceId',
  `status` enum('draft','generated','paid') NOT NULL DEFAULT 'draft',
  `formData` text NOT NULL COMMENT 'JSON PcaFormData',
  `aiResult` text COMMENT 'JSON PcaAiResult, NULL hasta generar',
  `clientTransactionId` varchar(64) COMMENT 'PayPhone clientTxId para el pago',
  `payphoneTransactionId` int COMMENT 'ID transaccion PayPhone tras pago exitoso',
  `authorizationCode` varchar(64),
  `amountPaid` int COMMENT 'centavos, siempre 1499',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pca_sessionId` (`sessionId`),
  KEY `idx_pca_clientTxId` (`clientTransactionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
